using Windows.Win32.Graphics.Dwm;
namespace WinWrapper.Windowing;
[Flags]
public enum DwmWindowAttribute
{
    DWMWA_NCRENDERING_ENABLED = DWMWINDOWATTRIBUTE.DWMWA_NCRENDERING_ENABLED,
    DWMWA_NCRENDERING_POLICY = DWMWINDOWATTRIBUTE.DWMWA_NCRENDERING_POLICY,
    DWMWA_TRANSITIONS_FORCEDISABLED = DWMWINDOWATTRIBUTE.DWMWA_TRANSITIONS_FORCEDISABLED,
    DWMWA_ALLOW_NCPAINT = DWMWINDOWATTRIBUTE.DWMWA_ALLOW_NCPAINT,
    DWMWA_CAPTION_BUTTON_BOUNDS = DWMWINDOWATTRIBUTE.DWMWA_CAPTION_BUTTON_BOUNDS,
    DWMWA_NONCLIENT_RTL_LAYOUT = DWMWINDOWATTRIBUTE.DWMWA_NONCLIENT_RTL_LAYOUT,
    DWMWA_FORCE_ICONIC_REPRESENTATION = DWMWINDOWATTRIBUTE.DWMWA_FORCE_ICONIC_REPRESENTATION,
    DWMWA_FLIP3D_POLICY = DWMWINDOWATTRIBUTE.DWMWA_FLIP3D_POLICY,
    DWMWA_EXTENDED_FRAME_BOUNDS = DWMWINDOWATTRIBUTE.DWMWA_EXTENDED_FRAME_BOUNDS,
    DWMWA_HAS_ICONIC_BITMAP = DWMWINDOWATTRIBUTE.DWMWA_HAS_ICONIC_BITMAP,
    DWMWA_DISALLOW_PEEK = DWMWINDOWATTRIBUTE.DWMWA_DISALLOW_PEEK,
    DWMWA_EXCLUDED_FROM_PEEK = DWMWINDOWATTRIBUTE.DWMWA_EXCLUDED_FROM_PEEK,
    DWMWA_CLOAK = DWMWINDOWATTRIBUTE.DWMWA_CLOAK,
    DWMWA_CLOAKED = DWMWINDOWATTRIBUTE.DWMWA_CLOAKED,
    DWMWA_FREEZE_REPRESENTATION = DWMWINDOWATTRIBUTE.DWMWA_FREEZE_REPRESENTATION,
    DWMWA_PASSIVE_UPDATE_MODE = DWMWINDOWATTRIBUTE.DWMWA_PASSIVE_UPDATE_MODE,
    DWMWA_USE_HOSTBACKDROPBRUSH = DWMWINDOWATTRIBUTE.DWMWA_USE_HOSTBACKDROPBRUSH,
    DWMWA_USE_IMMERSIVE_DARK_MODE = DWMWINDOWATTRIBUTE.DWMWA_USE_IMMERSIVE_DARK_MODE,
    DWMWA_WINDOW_CORNER_PREFERENCE = DWMWINDOWATTRIBUTE.DWMWA_WINDOW_CORNER_PREFERENCE,
    DWMWA_BORDER_COLOR = DWMWINDOWATTRIBUTE.DWMWA_BORDER_COLOR,
    DWMWA_CAPTION_COLOR = DWMWINDOWATTRIBUTE.DWMWA_CAPTION_COLOR,
    DWMWA_TEXT_COLOR = DWMWINDOWATTRIBUTE.DWMWA_TEXT_COLOR,
    DWMWA_VISIBLE_FRAME_BORDER_THICKNESS = DWMWINDOWATTRIBUTE.DWMWA_VISIBLE_FRAME_BORDER_THICKNESS,
    SystemBackdropTypes = DWMWINDOWATTRIBUTE.DWMWA_SYSTEMBACKDROP_TYPE,
    DWMWA_LAST = DWMWINDOWATTRIBUTE.DWMWA_LAST,
}