using Windows.Win32.UI.WindowsAndMessaging;
namespace WinWrapper.Windowing;

[Flags]
public enum WindowLongPtrIndex
{
    GWL_ExStyle = WINDOW_LONG_PTR_INDEX.GWL_EXSTYLE,
    GWLP_HINSTANCE = WINDOW_LONG_PTR_INDEX.GWLP_HINSTANCE,
    GWLP_HWNDPARENT = WINDOW_LONG_PTR_INDEX.GWLP_HWNDPARENT,
    GWLP_ID = WINDOW_LONG_PTR_INDEX.GWLP_ID,
    GWL_Style = WINDOW_LONG_PTR_INDEX.GWL_STYLE,
    GWLP_USERDATA = WINDOW_LONG_PTR_INDEX.GWLP_USERDATA,
    GWLP_WNDPROC = WINDOW_LONG_PTR_INDEX.GWLP_WNDPROC,
    GWL_HINSTANCE = WINDOW_LONG_PTR_INDEX.GWL_HINSTANCE,
    GWL_ID = WINDOW_LONG_PTR_INDEX.GWL_ID,
    GWL_USERDATA = WINDOW_LONG_PTR_INDEX.GWL_USERDATA,
    GWL_WNDPROC = WINDOW_LONG_PTR_INDEX.GWL_WNDPROC,
    GWL_HWNDPARENT = WINDOW_LONG_PTR_INDEX.GWL_HWNDPARENT,
}
