using Windows.Win32.UI.WindowsAndMessaging;
namespace WinWrapper;
[Flags]
public enum WindowClassLongIndex
{
    GCW_ATOM = GET_CLASS_LONG_INDEX.GCW_ATOM,
    GCL_CBCLSEXTRA = GET_CLASS_LONG_INDEX.GCL_CBCLSEXTRA,
    GCL_CBWNDEXTRA = GET_CLASS_LONG_INDEX.GCL_CBWNDEXTRA,
    GCL_HBRBACKGROUND = GET_CLASS_LONG_INDEX.GCL_HBRBACKGROUND,
    GCL_HCURSOR = GET_CLASS_LONG_INDEX.GCL_HCURSOR,
    GCL_HICON = GET_CLASS_LONG_INDEX.GCL_HICON,
    GCL_HICONSM = GET_CLASS_LONG_INDEX.GCL_HICONSM,
    GCL_HMODULE = GET_CLASS_LONG_INDEX.GCL_HMODULE,
    GCL_MENUNAME = GET_CLASS_LONG_INDEX.GCL_MENUNAME,
    GCL_STYLE = GET_CLASS_LONG_INDEX.GCL_STYLE,
    GCL_WNDPROC = GET_CLASS_LONG_INDEX.GCL_WNDPROC,
    GCLP_HBRBACKGROUND = GET_CLASS_LONG_INDEX.GCLP_HBRBACKGROUND,
    GCLP_HCURSOR = GET_CLASS_LONG_INDEX.GCLP_HCURSOR,
    GCLP_HICON = GET_CLASS_LONG_INDEX.GCLP_HICON,
    GCLP_HICONSM = GET_CLASS_LONG_INDEX.GCLP_HICONSM,
    GCLP_HMODULE = GET_CLASS_LONG_INDEX.GCLP_HMODULE,
    GCLP_MENUNAME = GET_CLASS_LONG_INDEX.GCLP_MENUNAME,
    GCLP_WNDPROC = GET_CLASS_LONG_INDEX.GCLP_WNDPROC,
}