using Windows.Win32.UI.WindowsAndMessaging;
namespace WinWrapper.Windowing;
[Flags]
public enum WindowExStyles : uint
{
    DLGMODALFRAME = WINDOW_EX_STYLE.WS_EX_DLGMODALFRAME,
    NOPARENTNOTIFY = WINDOW_EX_STYLE.WS_EX_NOPARENTNOTIFY,
    TOPMOST = WINDOW_EX_STYLE.WS_EX_TOPMOST,
    ACCEPTFILES = WINDOW_EX_STYLE.WS_EX_ACCEPTFILES,
    Transparent = WINDOW_EX_STYLE.WS_EX_TRANSPARENT,
    MDICHILD = WINDOW_EX_STYLE.WS_EX_MDICHILD,
    TOOLWINDOW = WINDOW_EX_STYLE.WS_EX_TOOLWINDOW,
    WINDOWEDGE = WINDOW_EX_STYLE.WS_EX_WINDOWEDGE,
    CLIENTEDGE = WINDOW_EX_STYLE.WS_EX_CLIENTEDGE,
    CONTEXTHELP = WINDOW_EX_STYLE.WS_EX_CONTEXTHELP,
    RIGHT = WINDOW_EX_STYLE.WS_EX_RIGHT,
    LEFT = WINDOW_EX_STYLE.WS_EX_LEFT,
    RTLREADING = WINDOW_EX_STYLE.WS_EX_RTLREADING,
    LTRREADING = WINDOW_EX_STYLE.WS_EX_LTRREADING,
    LEFTSCROLLBAR = WINDOW_EX_STYLE.WS_EX_LEFTSCROLLBAR,
    RIGHTSCROLLBAR = WINDOW_EX_STYLE.WS_EX_RIGHTSCROLLBAR,
    CONTROLPARENT = WINDOW_EX_STYLE.WS_EX_CONTROLPARENT,
    STATICEDGE = WINDOW_EX_STYLE.WS_EX_STATICEDGE,
    APPWINDOW = WINDOW_EX_STYLE.WS_EX_APPWINDOW,
    OVERLAPPEDWINDOW = WINDOW_EX_STYLE.WS_EX_OVERLAPPEDWINDOW,
    PALETTEWINDOW = WINDOW_EX_STYLE.WS_EX_PALETTEWINDOW,
    Layered = WINDOW_EX_STYLE.WS_EX_LAYERED,
    NOINHERITLAYOUT = WINDOW_EX_STYLE.WS_EX_NOINHERITLAYOUT,
    NOREDIRECTIONBITMAP = WINDOW_EX_STYLE.WS_EX_NOREDIRECTIONBITMAP,
    LAYOUTRTL = WINDOW_EX_STYLE.WS_EX_LAYOUTRTL,
    COMPOSITED = WINDOW_EX_STYLE.WS_EX_COMPOSITED,
    NOACTIVATE = WINDOW_EX_STYLE.WS_EX_NOACTIVATE
}