using Windows.Win32.UI.WindowsAndMessaging;
namespace WinWrapper;
[Flags]
public enum WindowStyles : uint
{
    OVERLAPPED = WINDOW_STYLE.WS_OVERLAPPED,
    POPUP = WINDOW_STYLE.WS_POPUP,
    CHILD = WINDOW_STYLE.WS_CHILD,
    MINIMIZE = WINDOW_STYLE.WS_MINIMIZE,
    Visible = WINDOW_STYLE.WS_VISIBLE,
    DISABLED = WINDOW_STYLE.WS_DISABLED,
    CLIPSIBLINGS = WINDOW_STYLE.WS_CLIPSIBLINGS,
    CLIPCHILDREN = WINDOW_STYLE.WS_CLIPCHILDREN,
    MAXIMIZE = WINDOW_STYLE.WS_MAXIMIZE,
    Caption = WINDOW_STYLE.WS_CAPTION,
    Border = WINDOW_STYLE.WS_BORDER,
    DLGFRAME = WINDOW_STYLE.WS_DLGFRAME,
    VSCROLL = WINDOW_STYLE.WS_VSCROLL,
    HSCROLL = WINDOW_STYLE.WS_HSCROLL,
    SYSMENU = WINDOW_STYLE.WS_SYSMENU,
    THICKFRAME = WINDOW_STYLE.WS_THICKFRAME,
    GROUP = WINDOW_STYLE.WS_GROUP,
    TABSTOP = WINDOW_STYLE.WS_TABSTOP,
    MINIMIZEBOX = WINDOW_STYLE.WS_MINIMIZEBOX,
    MAXIMIZEBOX = WINDOW_STYLE.WS_MAXIMIZEBOX,
    TILED = WINDOW_STYLE.WS_TILED,
    ICONIC = WINDOW_STYLE.WS_ICONIC,
    SizeBox = WINDOW_STYLE.WS_SIZEBOX,
    TILEDWINDOW = WINDOW_STYLE.WS_TILEDWINDOW,
    OverlappedWindow = WINDOW_STYLE.WS_OVERLAPPEDWINDOW,
    POPUPWINDOW = WINDOW_STYLE.WS_POPUPWINDOW,
    CHILDWINDOW = WINDOW_STYLE.WS_CHILDWINDOW,
    ACTIVECAPTION = WINDOW_STYLE.WS_ACTIVECAPTION
}